### ISSUE TITLE
Is there DarkComet in .NET Reactor from Danger Edition?

### ISSUE THREAD

**Issue by erxson** [simalei/njRAT#5]
I checked .NET Reactor from Danger Edition with virustotal.
https://www.virustotal.com/gui/file/79f190a51af8a463f13ddd5a76947cf7ba2adfb8e231b37c5e0968602217a62b/detection
Malwarebytes detects DarkComet RAT, so is it truth?

**Comment by YXCS1** [comment]
Uploading 202308301003.mov…

**Comment by erxson** [comment]
16 minutes uploading 202308301003.mov?

**Comment by Sindoes** [comment]
lol 
add violent_why on discord

**Comment by erxson** [comment]
:/
